spring:
  config:
    activate:
      on-profile: local

server:
  port: ${SERVER_PORT}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  storage:
    type: local
    root: ${FILE_STORAGE_ROOT}
